version: "24.0.6"
services:
  frontend:
    build:
      context: "./client"
      dockerfile: "./Dockerfile"
      target: dev
    networks:
      - node-network
    ports:
      - 3000:3000
  backend:
    build:
      context: "./server"
      dockerfile: "./Dockerfile"
    networks:
      - node-network
    depends_on:
      - postgres
    ports:
      - 5000:5000
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stuffJotter
    ports:
      - "5432:5432"
    networks:
      - node-network
    volumes:
      - ./sql/database.sql:/docker-entrypoint-initdb.d/database.sql
      - stuffJotterDB:/var/lib/postgresql/data
volumes:
  stuffJotterDB:
networks:
  node-network:
    driver: bridge
